import jwt

token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxMjAzNDU1LCJpYXQiOjE3MjExOTYxOTYsImp0aSI6IjhlZmVlYWRjNjgxMDRlMjE5Y2VhZDA3YTVkNDMwOWIxIiwidXNlcl9pZCI6OCwidXNlcl90eXBlIjoiZG9jdG9yIn0.O75DMtPQeGn-3CbOzJrPV2jG5Tuq6-lmaOAXh67YmTg"
decoded_token = jwt.decode(token, options={"verify_signature": False})
print(decoded_token)