# Generated by Django 5.0.6 on 2024-07-17 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hureapp', '0002_setofflinechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateField(default=datetime.datetime(2024, 7, 17, 4, 20, 44, 421445, tzinfo=datetime.timezone.utc)),
        ),
    ]
