# Generated by Django 5.0.6 on 2024-07-17 06:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_alter_doctor_number_alter_patient_number'),
        ('hureapp', '0003_appointment_date_of_appointment'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='appointment',
        #     name='end_time',
        #     field=models.TimeField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateField(default=datetime.date(2024, 7, 17)),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=300)),
                ('report', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('prescription', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('msgtype', models.CharField(max_length=100)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.doctor')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.patient')),
            ],
        ),
    ]
