# Generated by Django 5.0.6 on 2024-07-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hureapp', '0004_appointment_end_time_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='appointment',
        #     name='end_time',
        #     field=models.TimeField(blank=True, null=True),
        # ),
    ]
