# Generated by Django 5.0.6 on 2024-07-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_doctor_is_doctor_patient_is_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
