# Generated by Django 5.0.6 on 2024-07-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_remove_patient_is_patient_patient_is_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='is_doctor',
            new_name='is_patient',
        ),
    ]
