# Generated by Django 5.0.6 on 2024-07-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_rename_is_doctor_patient_is_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
